# Simplified Fly.io configuration for UE Hub Backend
app = "uehub"
primary_region = "ord"

[build]
  dockerfile = "infra/Dockerfile.backend"

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"
  API_PREFIX = "/v1"
  ENABLE_DOCS = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
