# Fly.io configuration for UE Hub Backend

app = "uehub"
primary_region = "ord"

[build]
  dockerfile = "infra/Dockerfile.backend"

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"
  API_PREFIX = "/v1"
  ENABLE_DOCS = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"

[checks]
  [checks.health]
    type = "http"
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"
  
  [checks.readiness]
    type = "http"
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/readyz"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  # release_command = "alembic upgrade head"

[[statics]]
  guest_path = "/app/uploads"
  url_prefix = "/files"
