# Docker Compose for local development

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: uehub
      POSTGRES_USER: uehub
      POSTGRES_PASSWORD: uehub_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uehub"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      # Use Neon database in development (comment out to use local postgres)
      - DATABASE_URL=postgresql+asyncpg://neondb_owner:npg_EoVzn0WyqX1v@ep-odd-tree-adxsa81s-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
      # - DATABASE_URL=postgresql+asyncpg://uehub:uehub_dev_password@postgres:5432/uehub  # Local postgres
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production-minimum-32-chars
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - NEON_API_ENDPOINT=https://ep-odd-tree-adxsa81s.apirest.c-2.us-east-1.aws.neon.tech/neondb/rest/v1
    volumes:
      - ../backend:/app
      - backend_uploads:/app/uploads
    depends_on:
      # postgres:  # Comment out when using Neon
      #   condition: service_healthy
      redis:
        condition: service_healthy
    command: ["python", "-m", "uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    environment:
      # Use Neon database in development
      - DATABASE_URL=postgresql+asyncpg://neondb_owner:npg_EoVzn0WyqX1v@ep-odd-tree-adxsa81s-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production-minimum-32-chars
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - NEON_API_ENDPOINT=https://ep-odd-tree-adxsa81s.apirest.c-2.us-east-1.aws.neon.tech/neondb/rest/v1
    volumes:
      - ../worker:/app/worker
      - backend_uploads:/app/uploads
    depends_on:
      # postgres:  # Comment out when using Neon
      #   condition: service_healthy
      redis:
        condition: service_healthy
    command: ["python", "-m", "worker.main"]

volumes:
  postgres_data:
  redis_data:
  backend_uploads:
