name: uehub-backend
region: nyc
services:
- name: api
  source_dir: /backend
  github:
    repo: easybandz777/UEhub
    branch: main
  run_command: uvicorn app.api:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: ENVIRONMENT
    value: production
  - key: LOG_LEVEL
    value: INFO
  - key: API_PREFIX
    value: /v1
  - key: ENABLE_DOCS
    value: "true"
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: ${DATABASE_URL}
    type: SECRET
  - key: SECRET_KEY
    value: ${SECRET_KEY}
    type: SECRET
  http_port: 8080
databases:
- name: uehub-db
  engine: PG
  version: "15"
  size: db-s-dev-database
